### PR TITLE
gpujpeg_reader: skip APP0 segments of unknown size

### PR DESCRIPTION
**Pull request by xqms**
... otherwise, those segments mess up the rest of the parse process.

### CODE REVIEW

**Comment by MartinPulec** [comment]
Hi Max,
thanks, yes, you are correct that this is not handled. On the other hand I don't think that the fix is yet entirely correct - the length AFAIK isn't 8 in general case, not even in case of JFIF/JFXX. If I am not mistaken, it is the following for JFIF:
1. marker length - 2 bytes
2. 'JFIF\0' - 5 bytes
3. [JFIF contents](https://exiftool.org/TagNames/JFIF.html) - 9 bytes
4. variable length thumbnail data

So it would actually skip every JFIF. Shouldn't the condition actually be _less then 7_ (minimal amount to be able to evaluate the nul-terminated 4 character tag)?

Thanks, Martin

**Comment by xqms** [comment]
Updated, thanks - I didn't know that the segment has variable size (and didn't read the code far enough) :see_no_evil:

I modified the check as you suggested - and also added skipping in the case the marker has sufficient size, but we do not recognize it.

I couldn't test this with the JPEG source that had this problem yet. I will do so later today.

**Comment by MartinPulec** [comment]
Ok, so I'll wait a moment before the merge. Otherwise it looks good to me - I'll perhaps re-add the the message identifying the unknown marker, but it may be only in the verbose mode.

**Comment by xqms** [comment]
Just tested it, works fine :+1:

I've still got sporadic decoding failures (1 in 1000 frames), but they are unrelated to the APP0 thing. I'll open a separate issue for them.

**Comment by MartinPulec** [comment]
Thanks. FYI, I've also added a check if the data read from APP0 is really a tag (i.e. is null-terminated). Otherwise it might segfault.

**Pull request merged**
